name: iOS - list schemes

on:
  push:
    branches: [ webxr ]
  workflow_dispatch:

jobs:
  list:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4

      # Пинним Xcode (попробуй 15.4)
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.4"

      - name: Xcode version
        run: xcodebuild -version

      - name: List schemes (Client.xcodeproj)
        run: xcodebuild -list -project Client.xcodeproj
